### ISSUE TITLE
How to create a "metafile"?

### ISSUE THREAD

**Issue by taschmidt** [floydspace/serverless-esbuild#121]
I tried adding `metafile: meta.json` but got an error from esbuild that metafile must be a boolean. So I changed it to `metafile: true`. The build ran successfully but I was never able to find any output. Has anyone managed to analyze their esbuild bundle sizes?

**Comment by floydspace** [comment]
hi @taschmidt, I checked the issue. As long as we are using esbuild's JavaScript API (not CLI), `metafile` option behaves a bit different, instead of defining a metafile name it receives a boolean value (according to `esbuild` source code, unfortunately it's not documented), and if the value is `true` the metadata is returned in the build result as JS object, so you can find your meta in the `result` variable here: https://github.com/floydspace/serverless-esbuild/blob/b5a9bdbe4be8b9decfda5590f92120d72ce8fe0e/src/index.ts#L229

**Comment by taschmidt** [comment]
Yeah sorry, I did do some digging in esbuild and saw that it appears you can only do it via code. It might be handy to check here if metafile is true and, if so, dump it out to meta.json or something.

**Comment by floydspace** [comment]
Hey @taschmidt , if it's still relevant for you, I completed the fix that will save metafile alongside the main bundle.

**Comment by taschmidt** [comment]
Awesome! Thanks so much!

**Comment by linonetwo** [comment]
Thanks, get it.

so we can have the solution:

```
const result = await esbuild.build({
  write: false,
  // we will have result.metafile later
  metafile: true,
  // other configs...
  entryPoints: packageJSON.tsFiles.map((tsFileName) => `./src/${tsFileName}.ts`),
  bundle: true,
  minify: false,
  sourcemap: process.env.CI ? false : 'inline',
  //....
});

// output bundle
for (let out of result.outputFiles) {
  await fs.mkdirp(path.dirname(out.path));
  await fs.writeFile(
    out.path,
    new TextDecoder()
      .decode(out.contents),
    'utf8',
  );
}

if (result.metafile) {
  // use https://bundle-buddy.com/esbuild to analyses
  await fs.writeFile('./dist/metafile.json', JSON.stringify(result.metafile));
}
```
