### ISSUE TITLE
Limit concurrency on esbuild packaging

### ISSUE THREAD

**Issue by JoaquinFernandez** [floydspace/serverless-esbuild#200]
Hi,

For some use cases, where there is limited system memory available (i.e. GitHub Actions 7GB), esbuild can run out of memory and crash when building a big serverless project (i.e. 50+ lambdas). For those cases, and according to the esbuild developer, it is recommended to do batching:

- https://github.com/evanw/esbuild/issues/320

In order to do so, and if I am not mistaken, the serverless-esbuild pack on here:

- https://github.com/floydspace/serverless-esbuild/blob/master/src/pack.ts#L113

Could use a library like [p-limit](https://github.com/sindresorhus/p-limit) or [p-queue](https://github.com/sindresorhus/p-queue) to limit the concurrent builds of lambdas, and configure the limit through an option in serverless.yml, for example under the key _concurrency_

Is that something that would make sense for this library or is it out of the scope of it?

If it would indeed make sense, is it something you would consider doing or would you accept a PR?

**Comment by floydspace** [comment]
Hi @JoaquinFernandez thank you for the issue, I personally haven't seen such big workloads, but yes it makes sense. We can also use `p-map` which has a more simplified interface.
And yes we accept PRs, but sometimes they could hang long, due to lack of time to review and test. So go ahead if you wish.
