### ISSUE TITLE
python import issues with serverless offline

### ISSUE THREAD

**Issue by ckjoris** [floydspace/serverless-esbuild#285]
getting this error in project with both node and python functions & serverless-offline. 
```
Traceback (most recent call last):
  File "myproject/node_modules/serverless-offline/dist/lambda/handler-runner/python-runner/invoke.py", line 76, in <module>

    module = import_module(args.handler_path.replace(os.sep, '.'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.esbuild..build.lambdas.tesseract'

```

I think its because the `pre-offline.js` modifies the path for all functions. If I manually comment out pre-offline.js (code in the conditional) - then python functions start to work, but obviously that breaks all nodejs functions.

`sls invoke local` works fine with both the python and node functions.

**Comment by samchungy** [comment]
Hey @ckjoris could you provide a sample repo to reproduce this? Thanks!

**Comment by samchungy** [comment]
> Hey @samchungy. Thanks for getting back to me. Here is a simple repo showing the issue: https://github.com/ckjoris/sls-esbuild-repro
> 
> It has two lambda functions defined, a nodejs & a python one. `yarn run serverless invoke local -f func_py` and `yarn run serverless invoke local -f func_node` work fine. However starting serverless-offline with `yarn run start`, then `curl http://localhost:5500/func_py` causes an python import issue

Thanks mate! I'm in the process of adding some integration tests so I'll include something similar.

**Comment by samchungy** [comment]
This is an issue actually with how serverless-offline loads python modules. https://github.com/dherault/serverless-offline/issues/993. I'll see if I can add customisation options for where things get outputted in our repo

**Comment by davidworkman9** [comment]
@samchungy I'm trying to implement the fix here and am still running into problems even with the new `outputBuildFolder` and `outputWorkFolder` options. I've forked @ckjoris's repo and applied the changes I think are necessary.

I originally ran into `esbuild` complaining about these two new options, which I believe the fix is to remove them from the build options before sending the options to esbuild. So I patched that using `patch-package`.

I was then presented with an error stating it cannot find the python module when I attempt to hit it via the API end point.

```    module = import_module(args.handler_path.replace(os.sep, '.'))
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myesbuild.mybuild.func_py'
```

The repo I cloned is here: https://github.com/davidworkman9/sls-esbuild-repro

Am I missing something else?
