### ISSUE TITLE
Is it possible to package aws-sdk with a single function only and exclude it for everything else?

### ISSUE THREAD

**Issue by joffarex** [floydspace/serverless-esbuild#407]
I have usecase where I need to be using a feature that is available in newer `aws-sdk` versions that is available in lambda's nodejs environment.

**Comment by floydspace** [comment]
Hi @joffarex 

Currently it's not possible configure individual lambdas bundle behaviour, but what you can try is `include` aws-sdk for all lambdas, especially AWS in some cases recommends including your own aws-sdk dependency, to avoid implicit assumption that you're using correct sdk version, (for instance node18.x runtime uses sdk v3, so if you simply update your runtime from older, your code may fail due to incorrect sdk api version)

**Comment by joffarex** [comment]
Thanks for an answer. We ended up mixing v2 and v3 sdk versions. So we are keep excluding v2 and including v3 in lambdas we need to (it gets treated as a separate package alltogether without any explicit configuration)

Unfortunately for my use case we can't include sdk in all lambdas since the project has grown too big as of now and build times would take more than half an hour if we were to do so. 

I'll close this one.
